---
AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  (WWPS-GLS-WF-ROOT) Scalable genomics workflows environment (Adapted from aws-genomics-root-novpc.template.yaml by @weeplang, @illusional, @delagoya)
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Required
        Parameters:
          - S3BucketName
          - ExistingBucket
          - WorkflowOrchestrator
          - VpcId
          - SubnetIds
      - Label:
          default: Optional
        Parameters:
          - SpotBidPercentage
          - DefaultCEMinvCpus
          - DefaultCEMaxvCpus
          - HighPriorityCEMinvCpus
          - HighPriorityCEMaxvCpus
          - TemplateRootUrl

    ParameterLabels:
      S3BucketName:
        default: S3 Bucket Name
      ExistingBucket:
        default: Existing Bucket?
      WorkflowOrchestrator:
        default: Workflow Orchestrator
      VpcId:
        default: VPC ID
      SubnetIds:
        default: VPC Subnet IDs
      SpotBidPercentage:
        default: Spot Bid %
      DefaultCEMinvCpus:
        default: Default Min vCPU
      DefaultCEMaxvCpus:
        default: Default Max vCPU
      HighPriorityCEMinvCpus:
        default: High Priority Min vCPU
      HighPriorityCEMaxvCpus:
        default: High Priority Max vCPU
      ArtifactRootUrl:
        default: Artifact Root URL
      TemplateRootUrl:
        default: Template Root URL


Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: 'The VPC to create security groups and deploy AWS Batch to. NOTE: Must be the same VPC as the provided subnet IDs.'
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: 'Subnets you want your batch compute environment to launch in. We recommend private subnets. NOTE: Must be from the VPC provided.'
  S3BucketName:
    Description: >-
      A S3 bucket name for storing analysis results.
      The bucket name must respect the S3 bucket naming conventions 
      (can contain lowercase letters, numbers, periods and hyphens).
    Type: String
    AllowedPattern: "((?=^.{3,63}$)(?!^(\\d+\\.)+\\d+$)(^(([a-z0-9]|[a-z0-9][a-z0-9\\-]*[a-z0-9])\\.)*([a-z0-9]|[a-z0-9][a-z0-9\\-]*[a-z0-9])$)|(^.{0}$))"
    ConstraintDescription: "Must respect AWS naming conventions"
  ExistingBucket:
    Description: Does this bucket already exist?
    Type: String
    AllowedValues:
      - Yes
      - No
    Default: No
  WorkflowOrchestrator:
    Description: The workflow orchestration engine you will use
    Type: String
    AllowedValues:
      - step-functions
      - cromwell
      - nextflow
    Default: step-functions
  SpotBidPercentage:
    Description: The percent of on-demand pricing for max bid for Spot intances
    Type: Number
    Default: 100
  DefaultCEMinvCpus:
    Description: The minimum number of CPUs for the default Batch Compute Environment
    Type: Number
    Default: 0
  DefaultCEMaxvCpus:
    Description: The maximum number of CPUs for the default Batch Compute Environment
    Type: Number
    Default: 100
  HighPriorityCEMinvCpus:
    Description: The minimum number of CPUs for the high-priority Batch Compute Environment
    Type: Number
    Default: 0
  HighPriorityCEMaxvCpus:
    Description: The maximum number of CPUs for the high-priority Batch Compute Environment
    Type: Number
    Default: 100
  ArtifactRootUrl:
    Type: String
    Default: https://s3.amazonaws.com/aws-genomics-workflows/artifacts
    Description: >-
      Root URL for where artifacts / additions scripts are stored
  TemplateRootUrl:
    Type: String
    Description: >-
      Root URL for where nested templates are stored
    Default: https://s3.amazonaws.com/aws-genomics-workflows/templates
    ConstraintDescription: >-
      Must be a valid S3 URL
    AllowedPattern: "https://s3(-[a-z0-9]+)*\\.amazonaws\\.com/[a-z0-9-./]{3,}"


Resources:
  S3Stack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    Properties:
      TemplateURL: !Sub ${TemplateRootUrl}/aws-genomics-s3.template.yaml
      TimeoutInMinutes: 5
      Parameters:
        S3BucketName: !Ref S3BucketName
        ExistingBucket: !Ref ExistingBucket
  
  IamStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    DependsOn: S3Stack
    Properties:
      TemplateURL: !Sub ${TemplateRootUrl}/aws-genomics-iam.template.yaml
      TimeoutInMinutes: 10
      Parameters:
        S3BucketName: !Sub ${S3Stack.Outputs.BucketName}
  
  LaunchTplStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    Properties:
      TemplateURL: !Sub ${TemplateRootUrl}/aws-genomics-launch-template.template.yaml
      Parameters:
        WorkflowOrchestrator: !Ref WorkflowOrchestrator
        ArtifactRootUrl: !Ref ArtifactRootUrl
  
  BatchStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    DependsOn:
      - IamStack
      - LaunchTplStack
    Properties:
      TemplateURL: !Sub ${TemplateRootUrl}/aws-genomics-batch.template.yaml
      TimeoutInMinutes: 10
      Parameters:
        LaunchTemplateId: !Sub ${LaunchTplStack.Outputs.LaunchTemplateId}
        VpcId: !Ref VpcId
        SubnetIds: !Join [",", !Ref SubnetIds ]
        SpotBidPercentage: !Ref SpotBidPercentage
        DefaultCEMinvCpus: !Ref DefaultCEMinvCpus
        DefaultCEMaxvCpus: !Ref DefaultCEMaxvCpus
        HighPriorityCEMinvCpus: !Ref HighPriorityCEMinvCpus
        HighPriorityCEMaxvCpus: !Ref HighPriorityCEMaxvCpus
        BatchServiceRoleArn: !Sub ${IamStack.Outputs.BatchServiceRoleArn}
        Ec2InstanceProfileArn: !Sub ${IamStack.Outputs.BatchInstanceProfileArn}
        SpotFleetRoleArn: !Sub ${IamStack.Outputs.BatchSpotFleetRoleArn}


Outputs:
  GenomicsEnvS3Bucket:
    Value: !Sub ${S3Stack.Outputs.BucketName}
    Export:
        Name: !Sub "${AWS::StackName}-Genomics-S3Bucket"
  GenomicsEnvBatchJobRoleArn:
    Value: !Sub ${IamStack.Outputs.BatchJobRoleArn}
    Export:
        Name: !Sub "${AWS::StackName}-Genomics-BatchJobRoleArn"
  GenomicsEnvDefaultJobQueueArn:
    Value: !Sub ${BatchStack.Outputs.DefaultJobQueueArn}
    Export:
        Name: !Sub "${AWS::StackName}-Genomics-DefaultJobQueueArn"
  GenomicsEnvHighPriorityJobQueueArn:
    Value: !Sub ${BatchStack.Outputs.HighPriorityJobQueueArn}
    Export:
        Name: !Sub "${AWS::StackName}-Genomics-HighPriorityJobQueueArn"
...